// GENERATED by tools/make_variant.sh V5 from RutaCryptoMirror.cs: same logic, renamed so it can be installed alongside other versions.
// =====================================================================================
//  RutaCryptoMirrorV5 - NinjaTrader 8 strategy
//
//  Bar-for-bar port of the TradingView Pine v4 strategy
//  "rutacrypto Optimized with Martingale and Leverage" (martingale / leverage removed).
//
//  Mirrored exactly (see README.md for the details and the reasons):
//   * Heikin Ashi open/close as returned by security(heikinashi(tickerid), timeframe.period, ...)
//     -> used only as a filter, orders fill at REAL prices, never at Heikin Ashi prices.
//   * Pine's own ema / rma / rsi / atr / sma math. NinjaTrader's built-in RSI / ATR / EMA
//     seed and smooth differently, so they are NOT used.
//   * RSI source = TradingView "Volume" indicator MA (SMA 10), RSI length 14 (your chart
//     settings, not the code defaults of close / 12).
//   * process_orders_on_close=true: every TradingView order fills at the CLOSE of the bar
//     that placed it.
//   * Stop loss / take profit are checked on the CLOSE only. There are no intrabar stop or
//     limit orders in the Pine script, so there are none here either.
//   * The exact order of the Pine script: SL/TP are overwritten by a new entry BEFORE the
//     exit block runs, and on a reversal TradingView flips the position with one order and
//     drops the same-bar close_all (your chart: "-47.2 Short" then "Take Profit +27.9").
//
//  Keep "Calculate" = On bar close and "Exit on session close" = false (both are the defaults).
// =====================================================================================

#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Gui;
using NinjaTrader.Gui.Chart;
using NinjaTrader.Gui.SuperDom;
using NinjaTrader.Gui.Tools;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.Core.FloatingPoint;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.DrawingTools;
#endregion

//This namespace holds Strategies in this folder and is required. Do not change it.
namespace NinjaTrader.NinjaScript.Strategies
{
	public class RutaCryptoMirrorV5 : Strategy
	{
		private const string TagPrefix = "RCM5_";

		private TvEngine engine;
		private int lastProcessedBar = -1;
		private SimpleFont orderFont;
		private SimpleFont signalFont;
		private SimpleFont statsFont;
		private StringBuilder barsCsv;

		protected override void OnStateChange()
		{
			if (State == State.SetDefaults)
			{
				Description = "NinjaTrader 8 mirror of the TradingView strategy 'rutacrypto Optimized' (fills at bar close, close-based SL/TP, Heikin Ashi + RSI of Volume MA). Martingale removed.";
				Name = "RutaCryptoMirrorV5";
				Calculate = Calculate.OnBarClose;
				EntriesPerDirection = 1;
				EntryHandling = EntryHandling.AllEntries;
				IsExitOnSessionCloseStrategy = false;	// TradingView never flattens at the session end
				ExitOnSessionCloseSeconds = 30;
				IsFillLimitOnTouch = false;
				MaximumBarsLookBack = MaximumBarsLookBack.TwoHundredFiftySix;
				OrderFillResolution = OrderFillResolution.Standard;
				Slippage = 0;
				StartBehavior = StartBehavior.WaitUntilFlat;
				TimeInForce = TimeInForce.Gtc;
				TraceOrders = false;
				RealtimeErrorHandling = RealtimeErrorHandling.StopCancelClose;
				StopTargetHandling = StopTargetHandling.PerEntryExecution;
				BarsRequiredToTrade = 200;			// warm-up: lets Pine's recursive averages converge
				IsInstantiatedOnEachOptimizationIteration = true;

				// Pine inputs, set to the values in your TradingView screenshots
				RsiUpper = 71;
				RsiLower = 20;
				VolumeThreshold = -39;
				StopLossAtrMultiplier = 2;
				TakeProfitAtrMultiplier = 4;
				OscShortLength = 5;
				OscLongLength = 14;
				RsiSource = RutaMirrorV5RsiSource.VolumeMA;
				RsiLength = 14;
				VolumeMaLength = 10;
				VolumeMaType = RutaMirrorV5MaType.SMA;

				// Hard-coded in the Pine script
				AtrLength = 14;
				TrendSmaLength = 10;
				RoundHeikinAshiToTick = false;

				// Exits: ATR + On bar close = TradingView
				ExitUnits = RutaMirrorV5ExitUnits.AtrMultiple;
				StopLossDollars = 1000;
				TakeProfitDollars = 1000;
				ExitExecution = RutaMirrorV5ExitExecution.OnBarClose;

				// Filter switches: all ON = TradingView. Turn off only to test / optimize.
				UseHeikinAshiFilter = true;
				UseVolumeFilter = true;
				UseTrendFilter = true;
				UsePdhPdlFilter = false;
				PdLevelPercent = 50;

				// Daily rules / trading hours: all off by default (= unchanged logic)
				DailyProfitGoal = 0;
				DailyGoalTolerance = 100;
				DailyMaxLoss = 0;
				BlockTradesOverDailyLoss = true;
				UseTradingHours = false;
				TradeStartTime = DateTime.Parse("09:30", CultureInfo.InvariantCulture);
				TradeEndTime = DateTime.Parse("16:00", CultureInfo.InvariantCulture);
				FlattenAtEndTime = true;

				// Position size (replaces martingale)
				SizingMode = RutaMirrorV5Sizing.FixedContracts;
				FixedContracts = 1;
				RiskPerTrade = 1000;
				MaxContracts = 10;

				// Execution / chart
				EnableOrders = true;
				ShowSignals = true;
				ShowTvFills = true;
				ShowTradeLines = true;
				ShowSkippedSetups = true;
				ShowStats = true;
				PrintTradeList = false;
				ExportTradesCsv = false;
				ExportBarsCsv = false;

				AddPlot(new Stroke(Brushes.Red, 2), PlotStyle.Line, "Stop Loss");
				AddPlot(new Stroke(Brushes.LimeGreen, 2), PlotStyle.Line, "Take Profit");
				AddPlot(new Stroke(Brushes.Goldenrod, 1), PlotStyle.Line, "PDH");
				AddPlot(new Stroke(Brushes.Goldenrod, 1), PlotStyle.Line, "PDL");
				AddPlot(new Stroke(Brushes.LimeGreen, DashStyleHelper.Dash, 1), PlotStyle.Line, "PD Long Level");
				AddPlot(new Stroke(Brushes.Red, DashStyleHelper.Dash, 1), PlotStyle.Line, "PD Short Level");
			}
			else if (State == State.DataLoaded)
			{
				TvEngine.Settings s = new TvEngine.Settings();
				s.RsiUpper = RsiUpper;
				s.RsiLower = RsiLower;
				s.VolumeThreshold = VolumeThreshold;
				s.SlAtrMult = StopLossAtrMultiplier;
				s.TpAtrMult = TakeProfitAtrMultiplier;
				s.OscShortLength = OscShortLength;
				s.OscLongLength = OscLongLength;
				s.RsiSource = RsiSource;
				s.RsiLength = RsiLength;
				s.VolumeMaLength = VolumeMaLength;
				s.VolumeMaType = VolumeMaType;
				s.AtrLength = AtrLength;
				s.TrendSmaLength = TrendSmaLength;
				s.RoundHaToTick = RoundHeikinAshiToTick;
				s.UseHeikinAshiFilter = UseHeikinAshiFilter;
				s.UseVolumeFilter = UseVolumeFilter;
				s.UseTrendFilter = UseTrendFilter;
				s.UsePdhPdlFilter = UsePdhPdlFilter;
				s.PdLevelPercent = PdLevelPercent;
				s.DailyProfitGoal = DailyProfitGoal;
				s.DailyGoalTolerance = DailyGoalTolerance;
				s.DailyMaxLoss = DailyMaxLoss;
				s.BlockOverDailyLoss = BlockTradesOverDailyLoss;
				s.UseTradingHours = UseTradingHours;
				s.TradeStart = TradeStartTime.TimeOfDay;
				s.TradeEnd = TradeEndTime.TimeOfDay;
				s.FlattenAtEnd = FlattenAtEndTime;
				s.ExitUnits = ExitUnits;
				s.StopLossDollars = StopLossDollars;
				s.TakeProfitDollars = TakeProfitDollars;
				s.ExitExecution = ExitExecution;
				s.TickSize = TickSize;
				s.PointValue = Instrument.MasterInstrument.PointValue;
				s.Sizing = SizingMode;
				s.FixedContracts = FixedContracts;
				s.RiskPerTrade = RiskPerTrade;
				s.MaxContracts = MaxContracts;
				engine = new TvEngine(s);

				lastProcessedBar = -1;
				orderFont = new SimpleFont("Arial", 11);
				orderFont.Bold = true;
				signalFont = new SimpleFont("Arial", 10);
				statsFont = new SimpleFont("Arial", 12);
				barsCsv = null;
				if (ExportBarsCsv)
				{
					barsCsv = new StringBuilder();
					barsCsv.AppendLine("nt_bar_time,tv_bar_time,open,high,low,close,volume,ha_open,ha_close,rsi_source,rsi,vol_osc,atr,sma_trend,longcond,shortcond,position_sign,pdh,pdl,pd_long_level,pd_short_level");
				}
			}
			else if (State == State.Transition)
			{
				if (engine != null)
				{
					Print(Name + " " + Instrument.FullName + " historical TV-mirror result: " + engine.SummaryLine());
					Print(Name + " " + engine.DiagnosticText(BarsRequiredToTrade).Replace("\n", " | "));
					Print(Name + " " + engine.SkippedSummary());
					foreach (string line in engine.SetupReport())
						Print(line);
				}
				WriteCsvFiles();
			}
			else if (State == State.Terminated)
			{
				WriteCsvFiles();
			}
		}

		protected override void OnBarUpdate()
		{
			if (BarsInProgress != 0 || engine == null)
				return;

			// Signals are evaluated on CLOSED bars only (TradingView default calc_on_every_tick=false).
			// With Calculate = OnEachTick/OnPriceChange the just-closed bar is processed on the first
			// tick of the next bar, which is the same moment an OnBarClose strategy runs.
			int ago = 0;
			if (Calculate != Calculate.OnBarClose && (State == State.Realtime || Bars.IsTickReplay))
			{
				if (!IsFirstTickOfBar)
					return;
				ago = 1;
			}
			int bar = CurrentBar - ago;
			if (bar < 0 || bar <= lastProcessedBar)
				return;
			lastProcessedBar = bar;

			TvEngine.BarResult r = engine.Update(bar, Time[ago], Open[ago], High[ago], Low[ago], Close[ago], Volume[ago], bar >= BarsRequiredToTrade,
				Bars.IsFirstBarOfSessionByIndex(bar));

			SetPlotValue(Values[0], ago, r.PlotStopLoss);
			SetPlotValue(Values[1], ago, r.PlotTakeProfit);
			// PDH / PDL lines while the filter is on; a one-bar gap at each new session avoids a vertical joint
			bool showLevels = UsePdhPdlFilter && !r.NewSession;
			SetPlotValue(Values[2], ago, showLevels ? r.Pdh : double.NaN);
			SetPlotValue(Values[3], ago, showLevels ? r.Pdl : double.NaN);
			SetPlotValue(Values[4], ago, showLevels ? r.PdLongLevel : double.NaN);
			SetPlotValue(Values[5], ago, showLevels ? r.PdShortLevel : double.NaN);

			if (EnableOrders)
				SubmitMirrorOrders(r);

			DrawBar(r, bar, ago);

			if (barsCsv != null)
				AppendBarCsv(r, ago);
		}

		#region Orders
		// Real NinjaTrader orders. Entries are market orders sent at the bar close, so NinjaTrader fills
		// them at the next tick (historical: the next bar's open). TradingView's simulated fill is the
		// close itself; that price is what the diamonds/labels and the stats box show.
		private void SubmitMirrorOrders(TvEngine.BarResult r)
		{
			if (r.EntryDirection != 0 && ExitExecution == RutaMirrorV5ExitExecution.StopTargetOrders)
			{
				// real stop + target (OCO) at the strategy's levels, attached when the entry fills
				string signal = r.EntryDirection > 0 ? "Long" : "Short";
				SetStopLoss(signal, CalculationMode.Price, r.EntryStop, false);
				SetProfitTarget(signal, CalculationMode.Price, r.EntryTarget);
			}

			if (r.EntryDirection > 0)
				EnterLong(r.QtyAfter, "Long");			// reverses a short automatically, like strategy.entry
			else if (r.EntryDirection < 0)
				EnterShort(r.QtyAfter, "Short");

			// On-close exits (TradingView). Stop/target-order exits were already filled by NinjaTrader itself.
			if (r.ExitComment != null && !r.ExitIntrabar)
			{
				if (r.ExitDirection > 0)
					ExitLong(r.ExitComment, "Long");
				else if (r.ExitDirection < 0)
					ExitShort(r.ExitComment, "Short");
			}
		}
		#endregion

		#region Chart drawing
		private static void SetPlotValue(Series<double> series, int barsAgo, double value)
		{
			if (double.IsNaN(value))
				series.Reset(barsAgo);
			else
				series[barsAgo] = value;
		}

		private void DrawBar(TvEngine.BarResult r, int bar, int ago)
		{
			if (ShowSignals)
			{
				// plotshape(longcond and strategy.position_size <= 0 ...) / plotshape(shortcond and strategy.position_size >= 0 ...)
				if (r.BuySignal)
					Draw.Text(this, TagPrefix + "sig" + bar, false, "Buy", ago, Low[ago], -14, Brushes.Black, signalFont, TextAlignment.Center, Brushes.Transparent, Brushes.LimeGreen, 90);
				if (r.SellSignal)
					Draw.Text(this, TagPrefix + "sig" + bar, false, "Sell", ago, High[ago], 14, Brushes.Black, signalFont, TextAlignment.Center, Brushes.Transparent, Brushes.Red, 90);
			}

			if (ShowTvFills)
			{
				bool entryIsBuy = r.EntryDirection > 0;
				if (r.ExitComment != null)
				{
					bool exitIsBuy = r.ExitDirection < 0;	// closing a short is a buy
					// with stop/target orders an exit and a new entry can share a bar: move the exit label further out
					int extraOffset = r.EntryDirection != 0 && exitIsBuy == entryIsBuy ? 34 : 0;
					DrawOrder("x" + bar, ago, exitIsBuy, r.ExitComment, r.ExitQty, Brushes.Magenta, r.ExitFillPrice, extraOffset);
				}
				if (r.EntryDirection != 0)
					DrawOrder(bar.ToString(CultureInfo.InvariantCulture), ago, entryIsBuy, entryIsBuy ? "Long" : "Short", r.EntryOrderQty,
						entryIsBuy ? Brushes.DodgerBlue : Brushes.Red, r.FillPrice, 0);
			}

			if (ShowTradeLines && r.ClosedTrade != null)
			{
				TvEngine.TvTrade t = r.ClosedTrade;
				Draw.Line(this, TagPrefix + "trade" + t.Number, false, t.EntryTime, t.EntryPrice, t.ExitTime, t.ExitPrice,
					t.Points > 0 ? Brushes.LimeGreen : Brushes.OrangeRed, DashStyleHelper.Dot, 2);
			}

			if (ShowSkippedSetups)
			{
				if (r.NewSkipped != null)
					foreach (TvEngine.Setup x in r.NewSkipped)
						DrawSkipped(x, Brushes.Gray, "");
				if (r.ResolvedCandidates != null)
					foreach (TvEngine.Setup x in r.ResolvedCandidates)
						if (!x.Taken)
							DrawSkipped(x, x.Outcome > 0 ? Brushes.LimeGreen : Brushes.OrangeRed, x.Outcome > 0 ? " (won)" : " (lost)");
			}

			if (r.ClosedTrade != null && PrintTradeList)
				Print(FormatTradeLine(r.ClosedTrade));

			if (r.DayDoneNow != null && ShowTvFills)
				Draw.Text(this, TagPrefix + "day" + bar, false, r.DayDoneNow == "daily goal" ? "DAILY GOAL - done for today" : "DAILY MAX LOSS - done for today",
					ago, High[ago], 80, r.DayDoneNow == "daily goal" ? Brushes.LimeGreen : Brushes.OrangeRed, signalFont, TextAlignment.Center, Brushes.Transparent, Brushes.Black, 60);

			// Status box: on every order, on the last historical bars and on every live bar, so it is
			// visible even when there are no trades (it then says which filter blocked them).
			bool lastHistoricalBar = State == State.Historical && CurrentBar >= Bars.Count - 2;
			if (ShowStats && (State != State.Historical || lastHistoricalBar || r.EntryDirection != 0 || r.ExitComment != null))
				Draw.TextFixed(this, TagPrefix + "stats", engine.StatsText(BarsRequiredToTrade), TextPosition.BottomLeft, Brushes.White, statsFont, Brushes.Gray, Brushes.Black, 70);
		}

		// A setup where the RSI trigger fired but no trade was taken, with the filters that blocked it.
		// Gray while undecided, then green / red once hindsight shows it would have hit TP / SL.
		private void DrawSkipped(TvEngine.Setup x, Brush brush, string result)
		{
			string text = (x.Direction > 0 ? "skip buy: " : "skip sell: ") + x.Blockers + result;
			Draw.Text(this, TagPrefix + "skip" + (x.Direction > 0 ? "L" : "S") + x.Bar, false, text, x.Time, x.LabelY, x.Direction > 0 ? -18 : 18,
				brush, signalFont, TextAlignment.Center, Brushes.Transparent, Brushes.Transparent, 0);
		}

		// TradingView style order marker: sells above the bar ("-qty" over the name), buys below
		// ("name" over "+qty"), and a diamond at the exact TradingView fill price (the bar close).
		private void DrawOrder(string key, int ago, bool isBuy, string name, int qty, Brush brush, double fillPrice, int extraOffset)
		{
			Draw.Diamond(this, TagPrefix + "px" + key, false, ago, fillPrice, brush);
			if (isBuy)
				Draw.Text(this, TagPrefix + "ord" + key, false, name + "\n+" + qty, ago, Low[ago], -46 - extraOffset, brush, orderFont, TextAlignment.Center, Brushes.Transparent, Brushes.Transparent, 0);
			else
				Draw.Text(this, TagPrefix + "ord" + key, false, "-" + qty + "\n" + name, ago, High[ago], 46 + extraOffset, brush, orderFont, TextAlignment.Center, Brushes.Transparent, Brushes.Transparent, 0);
		}
		#endregion

		#region Output window / CSV
		// TradingView "List of trades" shows the bar OPEN time; NinjaTrader stamps bars with their CLOSE time.
		private DateTime ToTvBarTime(DateTime ntBarTime)
		{
			if (BarsPeriod.BarsPeriodType == BarsPeriodType.Minute)
				return ntBarTime.AddMinutes(-BarsPeriod.Value);
			if (BarsPeriod.BarsPeriodType == BarsPeriodType.Second)
				return ntBarTime.AddSeconds(-BarsPeriod.Value);
			return ntBarTime;
		}

		private string FormatTradeLine(TvEngine.TvTrade t)
		{
			return string.Format(CultureInfo.InvariantCulture,
				"#{0} {1} {2} @ {3} (TV bar {4:yyyy-MM-dd HH:mm}) -> {5} @ {6} (TV bar {7:yyyy-MM-dd HH:mm})  {8:+0.00;-0.00} pts x{9}",
				t.Number, t.Direction > 0 ? "Long" : "Short", t.EntrySignal, t.EntryPrice, ToTvBarTime(t.EntryTime),
				t.ExitSignal, t.ExitPrice, ToTvBarTime(t.ExitTime), t.Points, t.Qty);
		}

		private void AppendBarCsv(TvEngine.BarResult r, int ago)
		{
			barsCsv.AppendLine(string.Format(CultureInfo.InvariantCulture,
				"{0:yyyy-MM-dd HH:mm:ss},{1:yyyy-MM-dd HH:mm:ss},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13},{14},{15},{16},{17},{18},{19},{20}",
				Time[ago], ToTvBarTime(Time[ago]), Open[ago], High[ago], Low[ago], Close[ago], Volume[ago],
				Num(r.HaOpen), Num(r.HaClose), Num(r.RsiSourceValue), Num(r.Rsi), Num(r.Osc), Num(r.Atr), Num(r.TrendMa),
				r.LongCond ? 1 : 0, r.ShortCond ? 1 : 0, r.PositionBefore, Num(r.Pdh), Num(r.Pdl), Num(r.PdLongLevel), Num(r.PdShortLevel)));
		}

		private static string Num(double v)
		{
			return double.IsNaN(v) ? "" : v.ToString("0.########", CultureInfo.InvariantCulture);
		}

		private string BuildTradesCsv()
		{
			StringBuilder sb = new StringBuilder();
			sb.AppendLine("Trade #,Type,Signal,Date/Time (TV bar open),NT bar time (close),Price,Contracts,Profit pts,Profit $,Cum. Profit $");
			double cum = 0;
			foreach (TvEngine.TvTrade t in engine.Trades)
			{
				string side = t.Direction > 0 ? "Long" : "Short";
				double money = t.Points * t.Qty * engine.PointValue;
				cum += money;
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "{0},Entry {1},{2},{3:yyyy-MM-dd HH:mm},{4:yyyy-MM-dd HH:mm},{5},{6},,,",
					t.Number, side, t.EntrySignal, ToTvBarTime(t.EntryTime), t.EntryTime, t.EntryPrice, t.Qty));
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "{0},Exit {1},{2},{3:yyyy-MM-dd HH:mm},{4:yyyy-MM-dd HH:mm},{5},{6},{7:0.00},{8:0.00},{9:0.00}",
					t.Number, side, t.ExitSignal, ToTvBarTime(t.ExitTime), t.ExitTime, t.ExitPrice, t.Qty, t.Points, money, cum));
			}
			return sb.ToString();
		}

		// Every bar where the RSI trigger fired, taken or not, with its filters and hindsight outcome
		private string BuildSetupsCsv()
		{
			StringBuilder sb = new StringBuilder();
			sb.AppendLine("nt_bar_time,tv_bar_time,side,rsi,ha_ok,vol_ok,sma_ok,pd_ok,pos_ok,taken,blocked_by,outcome,resolved_nt_time,r_multiple");
			foreach (TvEngine.Setup x in engine.Candidates)
			{
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "{0:yyyy-MM-dd HH:mm},{1:yyyy-MM-dd HH:mm},{2},{3:0.00},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13}",
					x.Time, ToTvBarTime(x.Time), x.Direction > 0 ? "long" : "short", x.Rsi, x.HaOk ? 1 : 0, x.VolOk ? 1 : 0, x.SmaOk ? 1 : 0, x.PdOk ? 1 : 0, x.PosOk ? 1 : 0,
					x.Taken ? 1 : 0, x.Blockers, x.Outcome > 0 ? "win" : x.Outcome < 0 ? "loss" : "open",
					x.ResolvedBar >= 0 ? x.ResolvedTime.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) : "",
					x.ResolvedBar >= 0 ? x.R.ToString("0.00", CultureInfo.InvariantCulture) : ""));
			}
			return sb.ToString();
		}

		private void WriteCsvFiles()
		{
			if (engine == null || (!ExportTradesCsv && barsCsv == null))
				return;
			try
			{
				string dir = System.IO.Path.Combine(NinjaTrader.Core.Globals.UserDataDir, "RutaCryptoMirrorV5");
				System.IO.Directory.CreateDirectory(dir);
				string baseName = SafeFileName(Instrument.FullName + "_" + BarsPeriod.Value + BarsPeriod.BarsPeriodType);
				if (ExportTradesCsv)
				{
					System.IO.File.WriteAllText(System.IO.Path.Combine(dir, baseName + "_trades.csv"), BuildTradesCsv());
					System.IO.File.WriteAllText(System.IO.Path.Combine(dir, baseName + "_setups.csv"), BuildSetupsCsv());
				}
				if (barsCsv != null)
					System.IO.File.WriteAllText(System.IO.Path.Combine(dir, baseName + "_bars.csv"), barsCsv.ToString());
				Print(Name + ": CSV written to " + dir);
			}
			catch (Exception ex)
			{
				Print(Name + ": CSV export failed: " + ex.Message);
			}
		}

		private static string SafeFileName(string name)
		{
			foreach (char c in System.IO.Path.GetInvalidFileNameChars())
				name = name.Replace(c, '_');
			return name.Replace(' ', '_');
		}
		#endregion

		#region TradingView engine (plain C#, no NinjaTrader calls)
		/// <summary>
		/// Bar-by-bar replica of the Pine script plus TradingView's broker emulator with
		/// process_orders_on_close=true. Call Update() once per CLOSED bar.
		/// </summary>
		public sealed class TvEngine
		{
			public sealed class Settings
			{
				public double RsiUpper = 71, RsiLower = 20, VolumeThreshold = -39, SlAtrMult = 2, TpAtrMult = 4;
				public int OscShortLength = 5, OscLongLength = 14;
				public RutaMirrorV5RsiSource RsiSource = RutaMirrorV5RsiSource.VolumeMA;
				public int RsiLength = 14, VolumeMaLength = 10;
				public RutaMirrorV5MaType VolumeMaType = RutaMirrorV5MaType.SMA;
				public int AtrLength = 14, TrendSmaLength = 10;
				public bool RoundHaToTick;
				public bool UseHeikinAshiFilter = true, UseVolumeFilter = true, UseTrendFilter = true;
				public bool UsePdhPdlFilter;		// off = unchanged logic
				public double PdLevelPercent = 100;	// 100 = PDH / PDL, 50 = middle of the previous session's range
				// Daily rules (a "day" = one session of the chart's Trading Hours) and trading hours. 0 / false = off.
				public double DailyProfitGoal, DailyGoalTolerance = 100, DailyMaxLoss;
				public bool BlockOverDailyLoss = true;
				public bool UseTradingHours, FlattenAtEnd = true;
				public TimeSpan TradeStart = new TimeSpan(9, 30, 0), TradeEnd = new TimeSpan(16, 0, 0);
				public RutaMirrorV5ExitUnits ExitUnits = RutaMirrorV5ExitUnits.AtrMultiple;
				public RutaMirrorV5ExitExecution ExitExecution = RutaMirrorV5ExitExecution.OnBarClose;
				public double StopLossDollars = 1000, TakeProfitDollars = 1000;
				public double TickSize = 0.25, PointValue = 1;
				public RutaMirrorV5Sizing Sizing = RutaMirrorV5Sizing.FixedContracts;
				public int FixedContracts = 1, MaxContracts = 10;
				public double RiskPerTrade = 1000;
			}

			public sealed class TvTrade
			{
				public int Number, Direction, Qty, EntryBar, ExitBar;
				public DateTime EntryTime, ExitTime;
				public double EntryPrice, ExitPrice;
				public double Points;			// per contract, positive = profit
				public string EntrySignal, ExitSignal;
			}

			public sealed class BarResult
			{
				public double HaOpen, HaClose, RsiSourceValue, Rsi, Osc, Atr, TrendMa;
				public double Pdh = double.NaN, Pdl = double.NaN;	// previous session high / low (NaN until one full session was seen)
				public double PdLongLevel = double.NaN, PdShortLevel = double.NaN;	// close must be above / below these (PDH/PDL filter)
				public bool NewSession;
				public string DayDoneNow;			// "daily goal" / "daily loss" when today's trading stopped on this bar
				public bool LongCond, ShortCond;		// raw Pine conditions
				public bool BuySignal, SellSignal;		// the two plotshape() conditions
				public double PlotStopLoss = double.NaN, PlotTakeProfit = double.NaN;	// plot(plotSL) / plot(plotTP)
				public int PositionBefore, PositionAfter;	// sign of strategy.position_size before / after this bar's fills
				public int QtyBefore, QtyAfter;
				public int EntryDirection;			// +1 / -1 when strategy.entry filled on this bar
				public int EntryOrderQty;			// TradingView order size (includes the reversed position)
				public double EntryStop = double.NaN, EntryTarget = double.NaN;	// levels of the position opened on this bar
				public double FillPrice = double.NaN;	// entry fill price (= close)
				public string ExitComment;			// "Take Profit" / "Stop Loss" when the position was closed by an exit
				public int ExitDirection, ExitQty;	// the position that exit closed
				public double ExitFillPrice = double.NaN;
				public bool ExitIntrabar;			// closed by a stop/target order inside the bar (ExitExecution = StopTargetOrders)
				public TvTrade ClosedTrade;			// trade closed on this bar (exit or reversal)
				public List<Setup> NewSkipped;		// RSI-trigger setups on this bar that were NOT traded
				public List<Setup> ResolvedCandidates;	// RSI-trigger setups whose hindsight outcome was decided on this bar
			}

			/// <summary>
			/// A possible entry at a bar's close, followed in hindsight with the strategy's own exit rule
			/// (SL / TP on the close). Used ONLY for the setup report and the chart markers, never to trade.
			/// </summary>
			public sealed class Setup
			{
				public int Bar, Direction, ResolvedBar = -1;
				public int Outcome;					// +1 take profit first, -1 stop loss first, 0 still open
				public DateTime Time, ResolvedTime;
				public double Entry, Stop, Target, Risk, LabelY, Rsi;
				public double R;					// result in R (1R = the stop distance)
				public bool Trigger, HaOk, VolOk, SmaOk, PdOk, PosOk, Taken;
				public string Blockers;				// e.g. "HA SMA", "in position", "" when taken
				public int Groups;					// report buckets this setup belongs to (bit mask)
			}

			public sealed class Bucket
			{
				public int N, Wins, Losses;
				public double SumR;
			}

			private readonly Settings s;
			private readonly PineMa emaShort, emaLong, volMa, trendMa;
			private readonly PineRsi rsi;
			private readonly PineAtr atr;

			private double haOpenPrev = double.NaN, haClosePrev = double.NaN, rsiPrev = double.NaN;

			// Pine 'var' variables: they keep their value until the next entry overwrites them
			private double stopLossLevel = double.NaN, profitTarget = double.NaN;

			// Broker emulator position
			private int position, positionQty, positionBar;
			private double positionPrice;
			private DateTime positionTime;

			private readonly List<TvTrade> trades = new List<TvTrade>();
			private int wins;
			private double grossProfitPts, grossLossPts, netMoney;

			// Diagnostics for the status box, so an empty chart explains itself
			private int barsSeen, rsiCrossUps, rsiCrossDowns, buySignals, sellSignals;
			private double minVolume = double.MaxValue, maxVolume = double.MinValue, lastRsi = double.NaN;
			private int sizedEntries, sumEntryQty, minEntryQty = int.MaxValue, maxEntryQty, entriesCapped, entriesRaised;

			// Previous session high / low
			private double sessionHigh = double.NaN, sessionLow = double.NaN, pdh = double.NaN, pdl = double.NaN;
			private bool sessionComplete;

			public TvEngine(Settings settings)
			{
				s = settings;
				emaShort = new PineEma(s.OscShortLength, 2.0 / (s.OscShortLength + 1));
				emaLong = new PineEma(s.OscLongLength, 2.0 / (s.OscLongLength + 1));
				volMa = CreateMa(s.VolumeMaType, s.VolumeMaLength);
				trendMa = new PineSma(s.TrendSmaLength);
				rsi = new PineRsi(s.RsiLength);
				atr = new PineAtr(s.AtrLength);
			}

			public List<TvTrade> Trades { get { return trades; } }
			public double PointValue { get { return s.PointValue; } }
			public int Position { get { return position; } }

			public BarResult Update(int barIndex, DateTime time, double open, double high, double low, double close, double volume, bool canTrade)
			{
				return Update(barIndex, time, open, high, low, close, volume, canTrade, false);
			}

			// isNewSession: this bar is the first bar of a trading session (the chart's Trading Hours template)
			public BarResult Update(int barIndex, DateTime time, double open, double high, double low, double close, double volume, bool canTrade, bool isNewSession)
			{
				BarResult r = new BarResult();

				// Previous session high / low. A session counts once it started at a real session boundary,
				// so a partial first session on the chart never becomes PDH / PDL.
				if (isNewSession)
				{
					if (sessionComplete)
					{
						pdh = sessionHigh;
						pdl = sessionLow;
					}
					sessionComplete = true;
					sessionHigh = high;
					sessionLow = low;
				}
				else
				{
					sessionHigh = double.IsNaN(sessionHigh) ? high : Math.Max(sessionHigh, high);
					sessionLow = double.IsNaN(sessionLow) ? low : Math.Min(sessionLow, low);
				}
				r.Pdh = pdh;
				r.Pdl = pdl;
				r.NewSession = isNewSession;
				if (isNewSession)
				{
					dayPnl = 0;
					dayTrades = 0;
					dayDoneReason = null;
				}

				// hclose / hopen = security(heikinashi(syminfo.tickerid), timeframe.period, close / open)
				double haClose = (open + high + low + close) / 4.0;
				double haOpen = double.IsNaN(haOpenPrev) ? (open + close) / 2.0 : (haOpenPrev + haClosePrev) / 2.0;
				haOpenPrev = haOpen;
				haClosePrev = haClose;
				double hclose = s.RoundHaToTick ? RoundToTick(haClose) : haClose;
				double hopen = s.RoundHaToTick ? RoundToTick(haOpen) : haOpen;

				// osc = 100 * (ema(volume, shortlen) - ema(volume, longlen)) / ema(volume, longlen)
				double shortEma = emaShort.Update(volume);
				double longEma = emaLong.Update(volume);
				double osc = (double.IsNaN(shortEma) || double.IsNaN(longEma) || longEma == 0) ? double.NaN : 100.0 * (shortEma - longEma) / longEma;

				// rsi1 = rsi(rsisrc, rsilen);  atr = atr(14);  trendma = sma(close, 10)
				double volMaValue = volMa.Update(volume);
				double src = SelectSource(open, high, low, close, volume, volMaValue);
				double rsi1 = rsi.Update(src);
				double atrValue = atr.Update(high, low, close);
				double trend = trendMa.Update(close);

				// crossover(rsi1, rsilower) / crossunder(rsi1, rsiupper). Comparisons with NaN are false, like na in Pine.
				bool crossUp = rsi1 > s.RsiLower && rsiPrev <= s.RsiLower;
				bool crossDown = rsi1 < s.RsiUpper && rsiPrev >= s.RsiUpper;
				rsiPrev = rsi1;

				barsSeen++;
				lastRsi = rsi1;
				minVolume = Math.Min(minVolume, volume);
				maxVolume = Math.Max(maxVolume, volume);

				// longcond / shortcond. Every filter switch is ON by default = TradingView; they exist for testing/optimizing.
				bool haLong = !s.UseHeikinAshiFilter || hclose > hopen;
				bool haShort = !s.UseHeikinAshiFilter || hclose < hopen;
				bool volOk = !s.UseVolumeFilter || osc > s.VolumeThreshold;
				bool smaLong = !s.UseTrendFilter || close > trend;
				bool smaShort = !s.UseTrendFilter || close < trend;
				// Optional PDH/PDL filter: longs only with the close above the previous session's high, shorts only below its low
				// Range Level %: longs need the close above PDL + level x range, shorts below PDH - level x range.
				// 100 = above PDH / below PDL, 50 = above / below the middle of the previous session's range.
				double pdRange = pdh - pdl;
				double pdLongLevel = pdl + s.PdLevelPercent / 100.0 * pdRange;
				double pdShortLevel = pdh - s.PdLevelPercent / 100.0 * pdRange;
				r.PdLongLevel = pdLongLevel;
				r.PdShortLevel = pdShortLevel;
				bool pdLong = !s.UsePdhPdlFilter || close > pdLongLevel;		// NaN (no full session yet) -> false while the filter is on
				bool pdShort = !s.UsePdhPdlFilter || close < pdShortLevel;
				bool longCond = haLong && crossUp && volOk && smaLong && pdLong;
				bool shortCond = haShort && crossDown && volOk && smaShort && pdShort;

				r.HaOpen = hopen;
				r.HaClose = hclose;
				r.RsiSourceValue = src;
				r.Rsi = rsi1;
				r.Osc = osc;
				r.Atr = atrValue;
				r.TrendMa = trend;
				r.LongCond = longCond;
				r.ShortCond = shortCond;

				if (!canTrade)
				{
					longCond = false;
					shortCond = false;
				}

				// ExitExecution = StopTargetOrders: the working stop and target orders can fill inside this bar,
				// before the close where the signals are evaluated. (TradingView mode checks the close instead, below.)
				bool intrabarExits = s.ExitExecution == RutaMirrorV5ExitExecution.StopTargetOrders;
				if (intrabarExits && position != 0)
				{
					double fill;
					int hit = IntrabarExit(position, stopLossLevel, profitTarget, open, high, low, out fill);
					if (hit != 0)
					{
						r.ExitComment = hit < 0 ? "Stop Loss" : "Take Profit";
						r.ExitDirection = position;
						r.ExitQty = positionQty;
						r.ExitFillPrice = fill;
						r.ExitIntrabar = true;
						r.ClosedTrade = CloseTrade(barIndex, time, fill, r.ExitComment);
						position = 0;
						positionQty = 0;
					}
				}

				// Trading hours (bar close time): no new entries outside the window; optionally flatten at the end time
				bool inHours = !s.UseTradingHours || InTradingWindow(time.TimeOfDay);
				if (!inHours && s.FlattenAtEnd && position != 0)
				{
					r.ExitComment = "End time";
					r.ExitDirection = position;
					r.ExitQty = positionQty;
					r.ExitFillPrice = close;
					r.ClosedTrade = CloseTrade(barIndex, time, close, r.ExitComment);
					position = 0;
					positionQty = 0;
				}

				// strategy.position_size as the script sees it (fills of earlier bars only)
				int pos = position;
				r.PositionBefore = pos;
				r.QtyBefore = positionQty;

				int sizeLimit;
				int newQty = ComputeQty(atrValue, out sizeLimit);
				double slDist = StopDistance(atrValue, newQty);		// ATR mode: atr * sl_multiplier, exactly as Pine
				double tpDist = TargetDistance(atrValue, newQty);

				// Which entry the Pine script would make, then the (optional) hours / daily rules gate
				int signalDir = 0;
				if (longCond && pos <= 0) signalDir = 1;
				if (shortCond && pos >= 0) signalDir = -1;
				string blockReason = signalDir != 0 ? EntryBlockReason(pos, close, slDist, newQty, inHours) : null;

				r.BuySignal = longCond && pos <= 0 && !(signalDir == 1 && blockReason != null);
				r.SellSignal = shortCond && pos >= 0 && !(signalDir == -1 && blockReason != null);
				if (canTrade)
				{
					if (crossUp) rsiCrossUps++;
					if (crossDown) rsiCrossDowns++;
					if (r.BuySignal) buySignals++;
					if (r.SellSignal) sellSignals++;
				}

				// Long Entry / Short Entry blocks: overwrite the levels first...
				int entryDir = 0;
				bool signalExit = false;
				if (signalDir != 0 && blockReason == null)
				{
					stopLossLevel = signalDir > 0 ? close - slDist : close + slDist;
					profitTarget = signalDir > 0 ? close + tpDist : close - tpDist;
					entryDir = signalDir;
				}
				else if (signalDir != 0 && pos != 0)
					signalExit = true;		// blocked reversal: the opposite signal still closes the open trade

				// ...then the exit block runs with the OLD position size and the (possibly NEW) levels
				bool takeProfitHit = (pos > 0 && close >= profitTarget) || (pos < 0 && close <= profitTarget);
				bool stopLossHit = (pos > 0 && close <= stopLossLevel) || (pos < 0 && close >= stopLossLevel);

				// plotSL / plotTP
				if (pos != 0 || entryDir != 0)
				{
					r.PlotStopLoss = stopLossLevel;
					r.PlotTakeProfit = profitTarget;
				}

				// Broker emulator, process_orders_on_close=true: everything fills at this bar's close.
				if (entryDir != 0)
				{
					// strategy.entry reverses an opposite position in ONE order (old qty + new qty).
					// The script's close_all calls on this bar are always true on a reversal bar (the levels
					// were just overwritten) and TradingView drops them - the position ends up reversed.
					r.EntryOrderQty = newQty + (pos != 0 ? positionQty : 0);
					sizedEntries++;
					sumEntryQty += newQty;
					minEntryQty = Math.Min(minEntryQty, newQty);
					maxEntryQty = Math.Max(maxEntryQty, newQty);
					if (sizeLimit > 0) entriesCapped++;
					if (sizeLimit < 0) entriesRaised++;
					if (pos != 0)
						r.ClosedTrade = CloseTrade(barIndex, time, close, entryDir > 0 ? "Long" : "Short");
					position = entryDir;
					positionQty = newQty;
					positionPrice = close;
					positionBar = barIndex;
					positionTime = time;
					r.EntryDirection = entryDir;
					r.EntryStop = stopLossLevel;
					r.EntryTarget = profitTarget;
					r.FillPrice = close;
				}
				else if (!intrabarExits && pos != 0 && (takeProfitHit || stopLossHit))
				{
					// strategy.close_all(comment="Take Profit") then strategy.close_all(comment="Stop Loss"): last call wins
					r.ExitComment = stopLossHit ? "Stop Loss" : "Take Profit";
					r.ExitDirection = pos;
					r.ExitQty = positionQty;
					r.ExitFillPrice = close;
					r.ClosedTrade = CloseTrade(barIndex, time, close, r.ExitComment);
					position = 0;
					positionQty = 0;
				}
				else if (signalExit)
				{
					r.ExitComment = "Signal exit";
					r.ExitDirection = pos;
					r.ExitQty = positionQty;
					r.ExitFillPrice = close;
					r.ClosedTrade = CloseTrade(barIndex, time, close, r.ExitComment);
					position = 0;
					positionQty = 0;
				}

				r.PositionAfter = position;
				r.QtyAfter = positionQty;
				r.DayDoneNow = dayDoneNow;
				dayDoneNow = null;

				// Setup report (hindsight, never used to trade): settle older setups on this close, then open this bar's
				ResolveSetups(barIndex, time, open, high, low, close, r);
				if (canTrade && atrValue > 0)
				{
					AddSetup(r, barIndex, time, close, atrValue, rsi1, 1, crossUp, haLong, volOk, smaLong, pdLong, pos <= 0, entryDir == 1, signalDir == 1 ? blockReason : null, low);
					AddSetup(r, barIndex, time, close, atrValue, rsi1, -1, crossDown, haShort, volOk, smaShort, pdShort, pos >= 0, entryDir == -1, signalDir == -1 ? blockReason : null, high);
				}
				return r;
			}

			#region Setup report
			private static readonly string[] BucketNames =
			{
				"Every bar, no filters (baseline)",
				"RSI cross (trigger only)",
				"RSI cross + Heikin Ashi",
				"RSI cross + HA + Volume osc",
				"All filters pass = signals",
				"Blocked ONLY by Heikin Ashi",
				"Blocked ONLY by Volume osc",
				"Blocked ONLY by SMA trend",
				"Blocked ONLY by PD range level",
				"Signal skipped: already in position",
				"Signal blocked: hours / daily rules"
			};
			private readonly Bucket[,] buckets = CreateBuckets();
			private readonly List<Setup> pending = new List<Setup>();
			private readonly List<Setup> candidates = new List<Setup>();

			public List<Setup> Candidates { get { return candidates; } }

			private static Bucket[,] CreateBuckets()
			{
				Bucket[,] b = new Bucket[BucketNames.Length, 2];
				for (int i = 0; i < BucketNames.Length; i++)
				{
					b[i, 0] = new Bucket();
					b[i, 1] = new Bucket();
				}
				return b;
			}

			private void AddSetup(BarResult r, int barIndex, DateTime time, double close, double atrValue, double rsiValue, int dir,
				bool trigger, bool haOk, bool volOk, bool smaOk, bool pdOk, bool posOk, bool taken, string entryBlock, double labelY)
			{
				Setup x = new Setup();
				x.Bar = barIndex;
				x.Time = time;
				x.Direction = dir;
				x.Entry = close;
				int qty = ComputeQty(atrValue);
				double slDist = StopDistance(atrValue, qty);
				double tpDist = TargetDistance(atrValue, qty);
				x.Risk = slDist;
				x.Stop = close - dir * slDist;		// same levels as the entry blocks
				x.Target = close + dir * tpDist;
				x.LabelY = labelY;
				x.Rsi = rsiValue;
				x.Trigger = trigger;
				x.HaOk = haOk;
				x.VolOk = volOk;
				x.SmaOk = smaOk;
				x.PdOk = pdOk;
				x.PosOk = posOk;
				x.Taken = taken;

				int groups = 1;
				if (trigger)
				{
					groups |= 2;
					if (haOk) groups |= 4;
					if (haOk && volOk) groups |= 8;
					if (haOk && volOk && smaOk && pdOk) groups |= 16;
					int fails = (haOk ? 0 : 1) + (volOk ? 0 : 1) + (smaOk ? 0 : 1) + (pdOk ? 0 : 1);
					if (fails == 1)
						groups |= !haOk ? 32 : !volOk ? 64 : !smaOk ? 128 : 256;
					if (fails == 0 && !posOk)
						groups |= 512;
					if (fails == 0 && posOk && entryBlock != null)
						groups |= 1024;

					List<string> why = new List<string>();
					if (!haOk) why.Add("HA");
					if (!volOk) why.Add("VOL");
					if (!smaOk) why.Add("SMA");
					if (!pdOk) why.Add(PdBlockerLabel(dir));
					if (why.Count == 0 && !posOk) why.Add("in position");
					if (why.Count == 0 && entryBlock != null) why.Add(entryBlock);
					x.Blockers = string.Join(" ", why.ToArray());

					candidates.Add(x);
					if (!taken)
					{
						if (r.NewSkipped == null)
							r.NewSkipped = new List<Setup>();
						r.NewSkipped.Add(x);
					}
				}
				x.Groups = groups;
				pending.Add(x);
			}

			private void ResolveSetups(int barIndex, DateTime time, double open, double high, double low, double close, BarResult r)
			{
				bool intrabarExits = s.ExitExecution == RutaMirrorV5ExitExecution.StopTargetOrders;
				for (int i = 0; i < pending.Count; i++)
				{
					Setup x = pending[i];
					double fill = close;
					int outcome;
					if (intrabarExits)
						outcome = IntrabarExit(x.Direction, x.Stop, x.Target, open, high, low, out fill);
					else
					{
						bool targetHit = x.Direction > 0 ? close >= x.Target : close <= x.Target;
						bool stopHit = x.Direction > 0 ? close <= x.Stop : close >= x.Stop;
						outcome = stopHit ? -1 : targetHit ? 1 : 0;		// same "last call wins" as the real exit block
					}
					if (outcome == 0)
						continue;
					x.Outcome = outcome;
					x.ResolvedBar = barIndex;
					x.ResolvedTime = time;
					x.R = (fill - x.Entry) * x.Direction / x.Risk;
					int side = x.Direction > 0 ? 0 : 1;
					for (int b = 0; b < BucketNames.Length; b++)
					{
						if ((x.Groups & (1 << b)) == 0)
							continue;
						Bucket k = buckets[b, side];
						k.N++;
						if (x.Outcome > 0) k.Wins++; else k.Losses++;
						k.SumR += x.R;
					}
					if (x.Trigger)
					{
						if (r.ResolvedCandidates == null)
							r.ResolvedCandidates = new List<Setup>();
						r.ResolvedCandidates.Add(x);
					}
					pending.RemoveAt(i);
					i--;
				}
			}

			public string SkippedSummary()
			{
				int n = 0, won = 0, lost = 0;
				foreach (Setup x in candidates)
				{
					if (x.Taken)
						continue;
					n++;
					if (x.Outcome > 0) won++;
					else if (x.Outcome < 0) lost++;
				}
				return string.Format(CultureInfo.InvariantCulture, "Skipped RSI setups: {0}  (in hindsight: would have won {1}, lost {2}, still open {3})", n, won, lost, n - won - lost);
			}

			public List<string> SetupReport()
			{
				List<string> lines = new List<string>();
				double sl = s.ExitUnits != RutaMirrorV5ExitUnits.AtrMultiple ? s.StopLossDollars : s.SlAtrMult;
				double tp = s.ExitUnits != RutaMirrorV5ExitUnits.AtrMultiple ? s.TakeProfitDollars : s.TpAtrMult;
				lines.Add(string.Format(CultureInfo.InvariantCulture,
					"SETUP REPORT (hindsight): every possible entry at the bar close, exited by the strategy's own rule ({0}). Break-even win rate ~{1:0.0}%. avg R > 0 = that group makes money.",
					ExitRuleText(), 100.0 * sl / (sl + tp)));
				string sizeStats = SizeStatsText();
				if (sizeStats != null)
					lines.Add("  " + sizeStats);
				for (int b = 0; b < BucketNames.Length; b++)
					lines.Add(string.Format(CultureInfo.InvariantCulture, "  {0,-38} | LONG  {1} | SHORT  {2}",
						BucketNames[b], FormatBucket(buckets[b, 0]), FormatBucket(buckets[b, 1])));
				return lines;
			}

			private static string FormatBucket(Bucket k)
			{
				if (k.N == 0)
					return "n=0".PadRight(34);
				return string.Format(CultureInfo.InvariantCulture, "n={0,5}  win {1,5:0.0}%  avg R {2,6:+0.00;-0.00}", k.N, 100.0 * k.Wins / k.N, k.SumR / k.N);
			}

			// Machine-readable buckets (used by the automated checks)
			public List<string> BucketRows()
			{
				List<string> rows = new List<string>();
				for (int b = 0; b < BucketNames.Length; b++)
					for (int side = 0; side < 2; side++)
						rows.Add(string.Format(CultureInfo.InvariantCulture, "{0},{1},{2},{3},{4},{5:R}", b, side == 0 ? "long" : "short",
							buckets[b, side].N, buckets[b, side].Wins, buckets[b, side].Losses, buckets[b, side].SumR));
				return rows;
			}
			#endregion

			private TvTrade CloseTrade(int barIndex, DateTime time, double price, string exitSignal)
			{
				TvTrade t = new TvTrade();
				t.Number = trades.Count + 1;
				t.Direction = position;
				t.Qty = positionQty;
				t.EntryBar = positionBar;
				t.EntryTime = positionTime;
				t.EntryPrice = positionPrice;
				t.EntrySignal = position > 0 ? "Long" : "Short";
				t.ExitBar = barIndex;
				t.ExitTime = time;
				t.ExitPrice = price;
				t.ExitSignal = exitSignal;
				t.Points = (price - positionPrice) * position;
				trades.Add(t);

				if (t.Points > 0)
				{
					wins++;
					grossProfitPts += t.Points * t.Qty;
				}
				else
					grossLossPts -= t.Points * t.Qty;
				netMoney += t.Points * t.Qty * s.PointValue;

				// today's result (closed trades, before commissions) and the daily rules
				dayPnl += t.Points * t.Qty * s.PointValue;
				dayTrades++;
				if (dayDoneReason == null)
				{
					if (s.DailyProfitGoal > 0 && dayPnl >= s.DailyProfitGoal - s.DailyGoalTolerance)
						dayDoneReason = "daily goal";
					else if (s.DailyMaxLoss > 0 && dayPnl <= -s.DailyMaxLoss)
						dayDoneReason = "daily loss";
					if (dayDoneReason != null)
						dayDoneNow = dayDoneReason;
				}
				return t;
			}

			// Daily rules state
			private double dayPnl;
			private int dayTrades;
			private string dayDoneReason, dayDoneNow;

			private bool InTradingWindow(TimeSpan t)
			{
				if (s.TradeStart == s.TradeEnd)
					return true;
				if (s.TradeStart < s.TradeEnd)
					return t >= s.TradeStart && t < s.TradeEnd;
				return t >= s.TradeStart || t < s.TradeEnd;		// window across midnight, e.g. 18:00 -> 16:45
			}

			// Why a new entry is not allowed right now (null = allowed). A reversal closes the open trade first,
			// so its result counts toward today's total before the new trade is judged.
			private string EntryBlockReason(int pos, double close, double slDist, int qty, bool inHours)
			{
				if (!inHours)
					return "hours";
				if (dayDoneReason != null)
					return dayDoneReason;
				double dayAfterClose = dayPnl;
				if (pos != 0)
					dayAfterClose += (close - positionPrice) * pos * positionQty * s.PointValue;
				if (s.DailyProfitGoal > 0 && dayAfterClose >= s.DailyProfitGoal - s.DailyGoalTolerance)
					return "daily goal";
				if (s.DailyMaxLoss > 0 && dayAfterClose <= -s.DailyMaxLoss)
					return "daily loss";
				if (s.DailyMaxLoss > 0 && s.BlockOverDailyLoss && dayAfterClose - slDist * qty * s.PointValue < -s.DailyMaxLoss)
					return "loss room";		// this trade's full stop would break the daily max loss
				return null;
			}

			private bool DailyRulesOn
			{
				get { return s.DailyProfitGoal > 0 || s.DailyMaxLoss > 0 || s.UseTradingHours; }
			}

			// Stop / target distance in points for a new position of 'qty' contracts
			private double StopDistance(double atrValue, int qty)
			{
				return s.ExitUnits != RutaMirrorV5ExitUnits.AtrMultiple ? DollarsToPoints(s.StopLossDollars, qty) : atrValue * s.SlAtrMult;
			}

			private double TargetDistance(double atrValue, int qty)
			{
				return s.ExitUnits != RutaMirrorV5ExitUnits.AtrMultiple ? DollarsToPoints(s.TakeProfitDollars, qty) : atrValue * s.TpAtrMult;
			}

			// $ for the whole position -> points, rounded to the tick. 1 NQ ($20/pt): $500 = 25 points.
			private double DollarsToPoints(double dollars, int qty)
			{
				double points = dollars / (Math.Max(1, qty) * s.PointValue);
				if (s.TickSize > 0)
					points = Math.Max(s.TickSize, Math.Round(points / s.TickSize) * s.TickSize);
				return points;
			}

			// Stop and target orders working during a bar. A gap through a level fills at the open. When one bar
			// touches both levels its OHLC can't tell which came first, so the stop is assumed (conservative).
			// Returns -1 stop, +1 target, 0 neither.
			private static int IntrabarExit(int dir, double stop, double target, double open, double high, double low, out double fill)
			{
				fill = double.NaN;
				if (dir > 0)
				{
					if (open <= stop) { fill = open; return -1; }
					if (open >= target) { fill = open; return 1; }
					if (low <= stop) { fill = stop; return -1; }
					if (high >= target) { fill = target; return 1; }
				}
				else if (dir < 0)
				{
					if (open >= stop) { fill = open; return -1; }
					if (open <= target) { fill = open; return 1; }
					if (high >= stop) { fill = stop; return -1; }
					if (low <= target) { fill = target; return 1; }
				}
				return 0;
			}

			// "PDH" / "PDL" at level 100 (as in V3), otherwise e.g. "PD50%"
			private string PdBlockerLabel(int dir)
			{
				if (s.PdLevelPercent == 100)
					return dir > 0 ? "PDH" : "PDL";
				return "PD" + s.PdLevelPercent.ToString("0.##", CultureInfo.InvariantCulture) + "%";
			}

			public string ExitRuleText()
			{
				string levels;
				if (s.ExitUnits == RutaMirrorV5ExitUnits.Dollars)
					levels = string.Format(CultureInfo.InvariantCulture, "SL ${0} / TP ${1} per position, {2} contract(s)", s.StopLossDollars, s.TakeProfitDollars, Math.Max(1, s.FixedContracts));
				else if (s.ExitUnits == RutaMirrorV5ExitUnits.DollarsSizedByAtr)
					levels = string.Format(CultureInfo.InvariantCulture, "SL ${0} / TP ${1} per position, contracts sized for a ~{2} ATR stop", s.StopLossDollars, s.TakeProfitDollars, s.SlAtrMult);
				else
					levels = string.Format(CultureInfo.InvariantCulture, "SL {0} ATR / TP {1} ATR", s.SlAtrMult, s.TpAtrMult);
				return levels + (s.ExitExecution == RutaMirrorV5ExitExecution.StopTargetOrders ? ", stop/target orders inside the bar" : ", checked on the close");
			}

			// Replaces the martingale/leverage sizing. RiskPerTrade is the non-martingale "USD" mode of the
			// Pine script: its qty = initial_size / (sl_multiplier * atr), i.e. it loses initial_size at the stop.
			//
			// DollarsSizedByAtr: contracts = floor(Stop Loss $ / (SL ATR multiplier x ATR x point value)), then the stop and
			// target are placed so the position loses exactly Stop Loss $ / wins exactly Take Profit $. Quiet market: tight
			// stop, more contracts; fast market: wide stop, fewer contracts.
			private int ComputeQty(double atrValue)
			{
				int limit;
				return ComputeQty(atrValue, out limit);
			}

			// limit: +1 capped at Max Contracts, -1 raised to the 1-contract minimum, 0 neither
			private int ComputeQty(double atrValue, out int limit)
			{
				limit = 0;
				if (s.ExitUnits == RutaMirrorV5ExitUnits.Dollars)
					return Math.Max(1, s.FixedContracts);
				double budget;
				if (s.ExitUnits == RutaMirrorV5ExitUnits.DollarsSizedByAtr)
					budget = s.StopLossDollars;
				else if (s.Sizing == RutaMirrorV5Sizing.RiskPerTrade)
					budget = s.RiskPerTrade;
				else
					return Math.Max(1, s.FixedContracts);
				double riskPerContract = atrValue * s.SlAtrMult * s.PointValue;
				if (double.IsNaN(riskPerContract) || riskPerContract <= 0)
					return 1;
				int maxQty = Math.Max(1, s.MaxContracts);
				double qty = Math.Floor(budget / riskPerContract);	// compared as double: no int overflow on a tiny ATR
				if (qty > maxQty) { limit = 1; return maxQty; }
				if (qty < 1) { limit = -1; return 1; }
				return (int)qty;
			}

			private bool SizesFromAtr
			{
				get { return s.ExitUnits == RutaMirrorV5ExitUnits.DollarsSizedByAtr || (s.ExitUnits == RutaMirrorV5ExitUnits.AtrMultiple && s.Sizing == RutaMirrorV5Sizing.RiskPerTrade); }
			}

			private string SizeStatsText()
			{
				if (!SizesFromAtr || sizedEntries == 0)
					return null;
				return string.Format(CultureInfo.InvariantCulture, "Contracts per entry: min {0}, max {1}, avg {2:0.0}   capped at Max Contracts {3}x, raised to 1 contract {4}x",
					minEntryQty, maxEntryQty, (double)sumEntryQty / sizedEntries, entriesCapped, entriesRaised);
			}

			private double SelectSource(double o, double h, double l, double c, double v, double volMaValue)
			{
				switch (s.RsiSource)
				{
					case RutaMirrorV5RsiSource.VolumeMA:	return volMaValue;
					case RutaMirrorV5RsiSource.Volume:	return v;
					case RutaMirrorV5RsiSource.Open:		return o;
					case RutaMirrorV5RsiSource.High:		return h;
					case RutaMirrorV5RsiSource.Low:		return l;
					case RutaMirrorV5RsiSource.HL2:		return (h + l) / 2.0;
					case RutaMirrorV5RsiSource.HLC3:		return (h + l + c) / 3.0;
					case RutaMirrorV5RsiSource.OHLC4:		return (o + h + l + c) / 4.0;
					default:							return c;
				}
			}

			// round_to_mintick(): nearest tick, ties up
			private double RoundToTick(double value)
			{
				if (s.TickSize <= 0)
					return value;
				return Math.Floor(value / s.TickSize + 0.5) * s.TickSize;
			}

			public string SummaryLine()
			{
				int n = trades.Count;
				return string.Format(CultureInfo.InvariantCulture, "{0} closed trades, win rate {1:0.0}%, net {2:+0.00;-0.00} pts x contracts, ${3:0.00}, profit factor {4}",
					n, n > 0 ? 100.0 * wins / n : 0.0, grossProfitPts - grossLossPts, netMoney,
					grossLossPts > 0 ? (grossProfitPts / grossLossPts).ToString("0.00", CultureInfo.InvariantCulture) : "n/a");
			}

			public string StatsText(int barsRequired)
			{
				int n = trades.Count;
				StringBuilder sb = new StringBuilder();
				bool tvMode = s.ExitUnits == RutaMirrorV5ExitUnits.AtrMultiple && s.ExitExecution == RutaMirrorV5ExitExecution.OnBarClose
					&& s.UseHeikinAshiFilter && s.UseVolumeFilter && s.UseTrendFilter && !s.UsePdhPdlFilter;
				sb.AppendLine(tvMode ? "RutaCryptoMirrorV5 - TradingView mirror (fills at bar close)" : "RutaCryptoMirrorV5 - CUSTOM settings (not the TradingView logic)");
				sb.AppendLine("Exits: " + ExitRuleText());
				if (s.UsePdhPdlFilter)
					sb.AppendLine(double.IsNaN(pdh)
						? "PDH/PDL filter ON - waiting for the first full session (no trades until then)"
						: string.Format(CultureInfo.InvariantCulture, "PDH/PDL filter ON at {0}% of the range - longs above {1}, shorts below {2}   (PDH {3}, PDL {4})",
							s.PdLevelPercent, pdl + s.PdLevelPercent / 100.0 * (pdh - pdl), pdh - s.PdLevelPercent / 100.0 * (pdh - pdl), pdh, pdl));
				string sizeStats = SizeStatsText();
				if (sizeStats != null)
					sb.AppendLine(sizeStats);
				if (DailyRulesOn)
				{
					string rules = "";
					if (s.DailyProfitGoal > 0)
						rules += string.Format(CultureInfo.InvariantCulture, "   goal ${0} (from ${1})", s.DailyProfitGoal, s.DailyProfitGoal - s.DailyGoalTolerance);
					if (s.DailyMaxLoss > 0)
						rules += string.Format(CultureInfo.InvariantCulture, "   max loss ${0}", s.DailyMaxLoss);
					if (s.UseTradingHours)
						rules += string.Format(CultureInfo.InvariantCulture, "   hours {0:hh\\:mm}-{1:hh\\:mm}{2}", s.TradeStart, s.TradeEnd, s.FlattenAtEnd ? " (flat at end)" : "");
					sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "Today: {0:+0.00;-0.00} $ in {1} trade(s) - {2}{3}",
						dayPnl, dayTrades, dayDoneReason == null ? "trading" : "DONE (" + dayDoneReason + ")", rules));
				}
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "Bars processed: {0}   (trades allowed from bar {1})", barsSeen, barsRequired));
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "Closed trades: {0}   Win rate: {1:0.0}%", n, n > 0 ? 100.0 * wins / n : 0.0));
				sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "Net: {0:+0.00;-0.00} pts x contracts   ${1:0.00}   Profit factor: {2}", grossProfitPts - grossLossPts, netMoney,
					grossLossPts > 0 ? (grossProfitPts / grossLossPts).ToString("0.00", CultureInfo.InvariantCulture) : "n/a"));
				if (position == 0)
					sb.AppendLine("Position: flat");
				else
					sb.AppendLine(string.Format(CultureInfo.InvariantCulture, "Position: {0} {1} @ {2}   SL {3:0.00}   TP {4:0.00}",
						position > 0 ? "Long" : "Short", positionQty, positionPrice, stopLossLevel, profitTarget));
				sb.AppendLine(SkippedSummary());
				sb.Append(DiagnosticText(barsRequired));
				return sb.ToString();
			}

			// Which filter is stopping trades, in plain words
			public string DiagnosticText(int barsRequired)
			{
				string text = string.Format(CultureInfo.InvariantCulture,
					"Since bar {0}: RSI crossed up {1}: {2}x, crossed down {3}: {4}x -> Buy signals {5}, Sell signals {6}   (RSI now {7})",
					barsRequired, s.RsiLower, rsiCrossUps, s.RsiUpper, rsiCrossDowns, buySignals, sellSignals,
					double.IsNaN(lastRsi) ? "n/a" : lastRsi.ToString("0.0", CultureInfo.InvariantCulture));
				if (barsSeen <= barsRequired)
					return text + string.Format(CultureInfo.InvariantCulture, "\nNOT ENOUGH DATA: only {0} bars loaded, the first {1} are warm-up. Load more days on the chart.", barsSeen, barsRequired);
				if (maxVolume <= minVolume)
					return text + string.Format(CultureInfo.InvariantCulture, "\nNO VOLUME: every bar has volume {0}. The RSI of the volume MA and the volume oscillator can never trigger on this data.", minVolume);
				if (rsiCrossUps + rsiCrossDowns == 0)
					return text + "\nThe RSI never crossed its levels. Check RSI Source / RSI Length / Volume MA Length.";
				if (buySignals + sellSignals == 0)
					return text + "\nThe RSI crossed, but the Heikin Ashi / volume oscillator / SMA filters rejected every cross.";
				return text;
			}

			private static PineMa CreateMa(RutaMirrorV5MaType type, int length)
			{
				switch (type)
				{
					case RutaMirrorV5MaType.EMA:	return new PineEma(length, 2.0 / (length + 1));
					case RutaMirrorV5MaType.RMA:	return new PineEma(length, 1.0 / length);
					case RutaMirrorV5MaType.WMA:	return new PineWma(length);
					default:					return new PineSma(length);
				}
			}

			#region Pine built-ins
			public abstract class PineMa
			{
				public abstract double Update(double x);
			}

			// sma(): na until 'length' values exist
			public sealed class PineSma : PineMa
			{
				private readonly double[] window;
				private int count, next;

				public PineSma(int length) { window = new double[Math.Max(1, length)]; }

				public override double Update(double x)
				{
					window[next] = x;
					next = (next + 1) % window.Length;
					if (count < window.Length)
						count++;
					if (count < window.Length)
						return double.NaN;
					double sum = 0;
					for (int i = 0; i < window.Length; i++)
						sum += window[i];
					return sum / window.Length;
				}
			}

			// ema() (alpha = 2/(len+1)) and rma() (alpha = 1/len): seeded with the SMA of the first
			// 'length' non-na values, na before that; na inputs are skipped.
			public sealed class PineEma : PineMa
			{
				private readonly int length;
				private readonly double alpha;
				private double seedSum, value = double.NaN;
				private int seedCount;

				public PineEma(int length, double alpha)
				{
					this.length = Math.Max(1, length);
					this.alpha = alpha;
				}

				public double Value { get { return value; } }

				public override double Update(double x)
				{
					if (double.IsNaN(x))
						return value;
					if (double.IsNaN(value))
					{
						seedSum += x;
						seedCount++;
						if (seedCount >= length)
							value = seedSum / length;
						return value;
					}
					value = alpha * x + (1 - alpha) * value;
					return value;
				}
			}

			// wma(): weights length..1, newest bar heaviest
			public sealed class PineWma : PineMa
			{
				private readonly double[] window;
				private int count, next;

				public PineWma(int length) { window = new double[Math.Max(1, length)]; }

				public override double Update(double x)
				{
					window[next] = x;
					next = (next + 1) % window.Length;
					if (count < window.Length)
						count++;
					if (count < window.Length)
						return double.NaN;
					int n = window.Length;
					double sum = 0, norm = 0;
					for (int i = 0; i < n; i++)
					{
						double w = n - i;			// i bars ago
						sum += window[((next - 1 - i) % n + n) % n] * w;
						norm += w;
					}
					return sum / norm;
				}
			}

			// rsi(x, len): rma of up/down changes; same edge cases as TradingView's RSI
			public sealed class PineRsi
			{
				private readonly PineEma up, down;
				private double prev = double.NaN;

				public PineRsi(int length)
				{
					up = new PineEma(length, 1.0 / Math.Max(1, length));
					down = new PineEma(length, 1.0 / Math.Max(1, length));
				}

				public double Update(double x)
				{
					if (!double.IsNaN(x) && !double.IsNaN(prev))
					{
						up.Update(Math.Max(x - prev, 0));
						down.Update(Math.Max(prev - x, 0));
					}
					prev = x;
					double u = up.Value, d = down.Value;
					if (double.IsNaN(u) || double.IsNaN(d))
						return double.NaN;
					if (d == 0)
						return 100;
					if (u == 0)
						return 0;
					return 100.0 - 100.0 / (1.0 + u / d);
				}
			}

			// atr(len) = rma(tr(true), len); the first bar's true range is high - low
			public sealed class PineAtr
			{
				private readonly PineEma rma;
				private double prevClose = double.NaN;

				public PineAtr(int length) { rma = new PineEma(length, 1.0 / Math.Max(1, length)); }

				public double Update(double high, double low, double close)
				{
					double tr = double.IsNaN(prevClose)
						? high - low
						: Math.Max(high - low, Math.Max(Math.Abs(high - prevClose), Math.Abs(low - prevClose)));
					prevClose = close;
					return rma.Update(tr);
				}
			}
			#endregion
		}
		#endregion

		#region Properties
		[NinjaScriptProperty]
		[Range(1.0, 1000.0)]
		[Display(Name = "RSI Upper Level", Description = "rsiupper - short needs RSI to cross DOWN through this level", Order = 1, GroupName = "1. Strategy Conditions (Pine)")]
		public double RsiUpper { get; set; }

		[NinjaScriptProperty]
		[Range(1.0, 1000.0)]
		[Display(Name = "RSI Lower Level", Description = "rsilower - long needs RSI to cross UP through this level", Order = 2, GroupName = "1. Strategy Conditions (Pine)")]
		public double RsiLower { get; set; }

		[NinjaScriptProperty]
		[Range(-1000.0, 1000.0)]
		[Display(Name = "Volume Increase Threshold", Description = "vollevel - volume oscillator must be above this", Order = 3, GroupName = "1. Strategy Conditions (Pine)")]
		public double VolumeThreshold { get; set; }

		[NinjaScriptProperty]
		[Range(0.1, double.MaxValue)]
		[Display(Name = "Stop Loss ATR Multiplier", Description = "AtrMultiple: stop distance in ATR. DollarsSizedByAtr: the stop width used to size the contracts. Ignored in Dollars mode.", Order = 4, GroupName = "1. Strategy Conditions (Pine)")]
		public double StopLossAtrMultiplier { get; set; }

		[NinjaScriptProperty]
		[Range(0.1, double.MaxValue)]
		[Display(Name = "Take Profit ATR Multiplier", Description = "AtrMultiple mode only. IGNORED in Dollars / DollarsSizedByAtr: the target comes from Take Profit ($).", Order = 5, GroupName = "1. Strategy Conditions (Pine)")]
		public double TakeProfitAtrMultiplier { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Stop/Target Units", Description = "AtrMultiple = TradingView (the two ATR multipliers above). Dollars = fixed $ with Fixed Contracts. DollarsSizedByAtr = fixed $, contracts sized so the stop is ~SL ATR multiplier x ATR.", Order = 6, GroupName = "1. Strategy Conditions (Pine)")]
		public RutaMirrorV5ExitUnits ExitUnits { get; set; }

		[NinjaScriptProperty]
		[Range(1.0, double.MaxValue)]
		[Display(Name = "Stop Loss ($)", Description = "Dollars modes: loss per position at the stop. 1 NQ: $500 = 25 points; 1 MNQ: $500 = 250 points.", Order = 7, GroupName = "1. Strategy Conditions (Pine)")]
		public double StopLossDollars { get; set; }

		[NinjaScriptProperty]
		[Range(1.0, double.MaxValue)]
		[Display(Name = "Take Profit ($)", Description = "Dollars modes: profit per position at the target.", Order = 8, GroupName = "1. Strategy Conditions (Pine)")]
		public double TakeProfitDollars { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Exit Execution", Description = "OnBarClose = TradingView (exit at the close once past the level; can overshoot). StopTargetOrders = real stop + target orders, exact levels.", Order = 9, GroupName = "1. Strategy Conditions (Pine)")]
		public RutaMirrorV5ExitExecution ExitExecution { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Short Length", Description = "Volume oscillator fast EMA", Order = 1, GroupName = "2. Volume Oscillator (Pine)")]
		public int OscShortLength { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Long Length", Description = "Volume oscillator slow EMA", Order = 2, GroupName = "2. Volume Oscillator (Pine)")]
		public int OscLongLength { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "RSI Source", Description = "Your TradingView chart uses 'Vol.: Volume MA' = VolumeMA", Order = 1, GroupName = "3. RSI (Pine)")]
		public RutaMirrorV5RsiSource RsiSource { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "RSI Length", Description = "Your TradingView chart uses 14 (the code default is 12)", Order = 2, GroupName = "3. RSI (Pine)")]
		public int RsiLength { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Volume MA Length", Description = "MA length of the TradingView Volume indicator you picked as RSI source", Order = 3, GroupName = "3. RSI (Pine)")]
		public int VolumeMaLength { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Volume MA Type", Description = "TradingView's built-in Volume indicator uses SMA", Order = 4, GroupName = "3. RSI (Pine)")]
		public RutaMirrorV5MaType VolumeMaType { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "ATR Length", Description = "Hard-coded atr(14) in Pine", Order = 1, GroupName = "4. Hard-coded in Pine")]
		public int AtrLength { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Trend SMA Length", Description = "Hard-coded sma(close, 10) in Pine", Order = 2, GroupName = "4. Hard-coded in Pine")]
		public int TrendSmaLength { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Round Heikin Ashi to tick", Description = "Only matters when HA open and close are within half a tick. Toggle if one rare trade differs.", Order = 3, GroupName = "4. Hard-coded in Pine")]
		public bool RoundHeikinAshiToTick { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Use Heikin Ashi filter", Description = "ON = TradingView. Turn off only to test / optimize.", Order = 1, GroupName = "8. Filter switches")]
		public bool UseHeikinAshiFilter { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Use Volume osc filter", Description = "ON = TradingView. Turn off only to test / optimize.", Order = 2, GroupName = "8. Filter switches")]
		public bool UseVolumeFilter { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Use SMA trend filter", Description = "ON = TradingView. Turn off only to test / optimize.", Order = 3, GroupName = "8. Filter switches")]
		public bool UseTrendFilter { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Use PDH/PDL filter", Description = "Longs only when the close is above the previous session's high, shorts only when it is below the previous session's low. Sessions follow the chart's Trading Hours (CME ETH: 6 pm to 5 pm New York). OFF = unchanged logic.", Order = 4, GroupName = "8. Filter switches")]
		public bool UsePdhPdlFilter { get; set; }

		[NinjaScriptProperty]
		[Range(0.0, 100.0)]
		[Display(Name = "PDH/PDL Range Level (%)", Description = "Where in the previous session's range the close must be. 100 = longs above PDH, shorts below PDL. 50 = longs above the middle of the range, shorts below it. 0 = longs above PDL, shorts below PDH.", Order = 5, GroupName = "8. Filter switches")]
		public double PdLevelPercent { get; set; }

		[NinjaScriptProperty]
		[Range(0.0, double.MaxValue)]
		[Display(Name = "Daily Profit Goal ($)", Description = "Stop opening trades for the rest of the session once today's closed trades reach this. 0 = off.", Order = 1, GroupName = "9. Daily rules & trading hours")]
		public double DailyProfitGoal { get; set; }

		[NinjaScriptProperty]
		[Range(0.0, double.MaxValue)]
		[Display(Name = "Daily Goal Tolerance ($)", Description = "The goal also counts as reached this much below it (goal 1500, tolerance 100: done from +1400). Covers ticks, slippage and fees.", Order = 2, GroupName = "9. Daily rules & trading hours")]
		public double DailyGoalTolerance { get; set; }

		[NinjaScriptProperty]
		[Range(0.0, double.MaxValue)]
		[Display(Name = "Daily Max Loss ($)", Description = "Stop opening trades for the rest of the session once today's closed trades lose this much. 0 = off.", Order = 3, GroupName = "9. Daily rules & trading hours")]
		public double DailyMaxLoss { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Block trades that could break max loss", Description = "Don't open a trade if hitting its full stop would take today past the Daily Max Loss.", Order = 4, GroupName = "9. Daily rules & trading hours")]
		public bool BlockTradesOverDailyLoss { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Use Trading Hours", Description = "Only open trades between Start and End time (the chart's time zone, bar close time). The window may cross midnight, e.g. 18:00 to 16:45.", Order = 5, GroupName = "9. Daily rules & trading hours")]
		public bool UseTradingHours { get; set; }

		[NinjaScriptProperty]
		[PropertyEditor("NinjaTrader.Gui.Tools.TimeEditorKey")]
		[Display(Name = "Start Time", Order = 6, GroupName = "9. Daily rules & trading hours")]
		public DateTime TradeStartTime { get; set; }

		[NinjaScriptProperty]
		[PropertyEditor("NinjaTrader.Gui.Tools.TimeEditorKey")]
		[Display(Name = "End Time", Order = 7, GroupName = "9. Daily rules & trading hours")]
		public DateTime TradeEndTime { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Flatten at End Time", Description = "Close any open trade on the first bar at or after the End Time.", Order = 8, GroupName = "9. Daily rules & trading hours")]
		public bool FlattenAtEndTime { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Sizing Mode", Description = "FixedContracts, or RiskPerTrade (= the Pine 'USD' sizing without martingale). Ignored in Dollars / DollarsSizedByAtr.", Order = 1, GroupName = "5. Position Size")]
		public RutaMirrorV5Sizing SizingMode { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Fixed Contracts", Description = "Used by FixedContracts sizing and by Dollars mode. Ignored in DollarsSizedByAtr.", Order = 2, GroupName = "5. Position Size")]
		public int FixedContracts { get; set; }

		[NinjaScriptProperty]
		[Range(1.0, double.MaxValue)]
		[Display(Name = "Risk Per Trade ($)", Description = "RiskPerTrade sizing with AtrMultiple units only: contracts = floor(risk / (SL ATR mult x ATR x point value)). Ignored in Dollars modes (there Stop Loss $ is the risk).", Order = 3, GroupName = "5. Position Size")]
		public double RiskPerTrade { get; set; }

		[NinjaScriptProperty]
		[Range(1, int.MaxValue)]
		[Display(Name = "Max Contracts", Description = "Safety cap for ATR sizing. In DollarsSizedByAtr a capped (or 1-contract) entry keeps the $ amounts, so its stop is wider (or tighter) than the ATR target.", Order = 4, GroupName = "5. Position Size")]
		public int MaxContracts { get; set; }

		[NinjaScriptProperty]
		[Display(Name = "Enable Orders", Description = "Off = only draw the TradingView trades (indicator mode)", Order = 1, GroupName = "6. Execution")]
		public bool EnableOrders { get; set; }

		[Display(Name = "Show Buy/Sell Signals", Order = 1, GroupName = "7. Chart / Compare")]
		public bool ShowSignals { get; set; }

		[Display(Name = "Show TradingView Fills", Description = "Order labels + diamond at the TradingView fill price (bar close)", Order = 2, GroupName = "7. Chart / Compare")]
		public bool ShowTvFills { get; set; }

		[Display(Name = "Show Trade Lines", Order = 3, GroupName = "7. Chart / Compare")]
		public bool ShowTradeLines { get; set; }

		[Display(Name = "Show Skipped Setups", Description = "RSI trigger fired but no trade: shows the blocking filter, turns green/red with the hindsight result", Order = 4, GroupName = "7. Chart / Compare")]
		public bool ShowSkippedSetups { get; set; }

		[Display(Name = "Show Stats Box", Order = 5, GroupName = "7. Chart / Compare")]
		public bool ShowStats { get; set; }

		[Display(Name = "Print Trades To Output", Order = 6, GroupName = "7. Chart / Compare")]
		public bool PrintTradeList { get; set; }

		[Display(Name = "Export Trades CSV", Description = "Documents\\NinjaTrader 8\\RutaCryptoMirrorV5\\<instrument>_trades.csv (+ _setups.csv)", Order = 7, GroupName = "7. Chart / Compare")]
		public bool ExportTradesCsv { get; set; }

		[Display(Name = "Export Bar Values CSV", Description = "Per-bar HA / RSI / osc / ATR values to compare with the debug Pine script", Order = 8, GroupName = "7. Chart / Compare")]
		public bool ExportBarsCsv { get; set; }
		#endregion
	}
}

public enum RutaMirrorV5RsiSource
{
	VolumeMA,
	Volume,
	Close,
	Open,
	High,
	Low,
	HL2,
	HLC3,
	OHLC4
}

public enum RutaMirrorV5MaType
{
	SMA,
	EMA,
	RMA,
	WMA
}

public enum RutaMirrorV5Sizing
{
	FixedContracts,
	RiskPerTrade
}

public enum RutaMirrorV5ExitUnits
{
	AtrMultiple,
	Dollars,
	DollarsSizedByAtr
}

public enum RutaMirrorV5ExitExecution
{
	OnBarClose,
	StopTargetOrders
}
