#!/usr/bin/env bash
# Writes ninjatrader/Strategies/RutaCryptoMirrorV2.cs: the same strategy with every global name renamed
# (class, display name, enums, CSV folder, drawing tags) so it installs next to any RutaCryptoMirror.cs.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/ninjatrader/Strategies/RutaCryptoMirror.cs"
dst="$root/ninjatrader/Strategies/RutaCryptoMirrorV2.cs"
{
  echo "// GENERATED by tools/make_v2.sh from RutaCryptoMirror.cs: same logic, renamed so both can be installed together."
  sed -e 's/RutaCryptoMirror/RutaCryptoMirrorV2/g' \
      -e 's/RutaMirror\([A-Z]\)/RutaMirrorV2\1/g' \
      -e 's/"RCM_"/"RCM2_"/' "$src"
} > "$dst"
echo "wrote $dst"
